version: '3.8'

services:
  gatos-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9009:9009"
    environment:
      - PORT=9009
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules